# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chat_pb2 as chat__pb2


class ChatAssistantStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetResponse = channel.unary_stream(
                '/ChatAssistant/GetResponse',
                request_serializer=chat__pb2.UserQuery.SerializeToString,
                response_deserializer=chat__pb2.AssistantReply.FromString,
                )


class ChatAssistantServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatAssistantServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetResponse': grpc.unary_stream_rpc_method_handler(
                    servicer.GetResponse,
                    request_deserializer=chat__pb2.UserQuery.FromString,
                    response_serializer=chat__pb2.AssistantReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ChatAssistant', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatAssistant(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ChatAssistant/GetResponse',
            chat__pb2.UserQuery.SerializeToString,
            chat__pb2.AssistantReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
