version: '3.8'

services:
  # ollama:
  #   image: ollama/ollama
  #   container_name: ollama
  #   # runtime: nvidia
  #   # environment:
  #   #   - NVIDIA_VISIBLE_DEVICES=all
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama:/root/.ollama
  #   # deploy:
  #   #   resources:
  #   #     reservations:
  #   #       devices:
  #   #         - driver: nvidia
  #   #           count: all
  #   #           capabilities: [gpu]

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  # ollama:
  redis_data:

