# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\"\x1c\n\tUserQuery\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"!\n\x0e\x41ssistantReply\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t2=\n\rChatAssistant\x12,\n\x0bGetResponse\x12\n.UserQuery\x1a\x0f.AssistantReply0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERQUERY']._serialized_start=14
  _globals['_USERQUERY']._serialized_end=42
  _globals['_ASSISTANTREPLY']._serialized_start=44
  _globals['_ASSISTANTREPLY']._serialized_end=77
  _globals['_CHATASSISTANT']._serialized_start=79
  _globals['_CHATASSISTANT']._serialized_end=140
# @@protoc_insertion_point(module_scope)
